---

- name: Install Orchestrator packages
  yum:
    name: "{{ package_list }}"
    state: latest

- name: Copy Orchestrator config file into place
  template:
    src: orchestrator.conf.json.j2
    dest: "{{ orc_conf }}"

- name: Create Orchestrator service for systemd
  template:
      src: orchestrator.service.j2
      dest: "{{ orc_systemd_service }}"

- name: Restart orchestrator
  service:
    name: orchestrator
    state: restarted
    enabled: yes

- name: Discover Orchestrator nodes
  command: orchestrator-client -c discover -i "{{ hostvars[item]['ansible_host'] }}"
  loop: "{{ groups[orc_cluster] }}"
