---

- hosts: async57
  become: yes
  vars:
    - source_ip: "{{ hostvars['mysql1']['ansible_host'] }}"
  roles:
    - {role: async57, tags: [ never, async57 ]}

- hosts: orchestrator
  become: yes
  roles:
    - {role: orchestrator, tags: [ never, orchestrator ]}
