---

orc_http_user: orchestrator
orc_http_password: Tantrum0-Reassign-Flatterer-Glaucoma

orc_version: 3.0.14

package_list: "jq,https://github.com/github/orchestrator/releases/download/v{{ orc_version }}/orchestrator-{{ orc_version }}-1.x86_64.rpm,https://github.com/github/orchestrator/releases/download/v{{ orc_version }}/orchestrator-client-{{ orc_version }}-1.x86_64.rpm"

orc_conf: /etc/orchestrator.conf.json
orc_systemd_service: /etc/systemd/system/orchestrator.service

config:
  #clusters: ["{{ orc_clusters }}"]
  UseSuperReadOnly: true
  AutoPseudoGTID: true
  MySQLTopologyUser: "{{ orc_mysql_user }}"
  MySQLTopologyPassword: "{{ orc_mysql_password }}"
  HostnameResolveMethod: none
  MySQLHostnameResolveMethod: ""
  HTTPAuthUser: "{{ orc_http_user }}"
  HTTPAuthPassword: "{{ orc_http_password }}"
  DetectClusterAliasQuery: ""
  ApplyMySQLPromotionAfterMasterFailover: true
  MasterFailoverDetachSlaveMasterHost: true
